argo-cd:
  server:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - ewolke.io
      pathType: "Exact"
#      ingressClassName: nginx